version: '3'

# under services you specify how many containers you
# want to create and which image/dockerfile to use
services:
  redis-server:
    image: 'redis'
  nope-app:
    build: .
    ports:
      - "8081:8081"